# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
