# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 01:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 24, 1, 51, 29, 35673, tzinfo=utc)),
        ),
    ]
